#! /usr/bin/env bash


rm -rf $HOME/programs/miniconda3
mkdir -p $HOME/programs/miniconda3
cd $HOME/programs/miniconda3

wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ./miniconda.sh
bash ./miniconda.sh -b -u -p $HOME/programs/miniconda3
rm ./miniconda.sh
